#!/bin/bash
######################################################################
# Show diff between contents in local or remote, especially GitHub.
######################################################################

set -eu

usage(){
    echo "Usage: gdiff FILE1 FILE2"
}

get_github_blob_content(){
    regexp="https://github.com/([^/]+)/([^/]+)/blob/([^/]+)/(.+)"
    endpoint_tmpl="repos/\1/\2/contents/\4?ref=\3"
    endpoint=$(echo ${1} | sed -r "s#${regexp}#${endpoint_tmpl}#g")
    if ! gh api ${endpoint} --silent 2> /dev/null; then
        gh api ${endpoint} --silent
    fi
    gh api ${endpoint} 2> /dev/null | jq -r .content | base64 -d
}

get_content(){
    github_blob_regexp="https://github.com/([^/]+)/([^/]+)/blob/([^/]+)/(.+)"
    http_regexp="https?://.+"
    if echo ${1} | egrep ${github_blob_regexp} > /dev/null; then
        get_github_blob_content ${1}
    elif echo ${1} | egrep ${http_regexp} > /dev/null; then
        curl -sL ${1}
    else
        cat ${1}
    fi
}

if [ $# -ne 2 ]; then
    usage
    exit 1
fi

file1=$(tempfile)
get_content ${1} > ${file1}

file2=$(tempfile)
get_content ${2} > ${file2}

diff -u -N --color=auto ${file1} ${file2}

rm ${file1} ${file2}
