#!/bin/bash

set -euo pipefail

COMMAND=$(basename "${0}")

function usage {
    cat <<EOF
NAME
    ${COMMAND}

SYNOPSIS
    ${COMMAND} [options] url ref1 ref2

DESCRIPTION
    Compare manifests built by kustomize from two different references in a github repository.

OPTIONS
    -h  help for ${COMMAND}
EOF
}

while getopts h OPT
do
    case $OPT in
        h) usage; exit;;
        *) usage; exit 1;;
    esac
done

if [ $# -ne 3 ]; then
    usage
    exit 1
fi

URL=${1}
REF1=${2}
REF2=${3}

BUILD="kustomize build --enable-alpha-plugins"

echo "$ diff <(${BUILD} ${URL}?ref=${REF1}) <(${BUILD} ${URL}?ref=${REF2})"
diff -u -N --color=auto <(${BUILD} "${URL}?ref=${REF1}") <(${BUILD} "${URL}?ref=${REF2}")
