#!/bin/bash

set -euo pipefail

COMMAND=$(basename "${0}")

function usage {
    cat <<EOF
NAME
    ${COMMAND}

SYNOPSIS
    ${COMMAND} [options]

DESCRIPTION
    Kubectl plugin for argo workflows.

OPTIONS
    -h  help for ${COMMAND}
EOF
}

argo "$@"
