#!/bin/bash
######################################################################
# Add script to generate istio manifests and reorder it by kustomize
######################################################################
WORKDIR=$(mktemp -d)
istioctl manifest generate $@ > $WORKDIR/generated.yaml
cd $WORKDIR
kustomize create --resources $WORKDIR/generated.yaml
kustomize build $WORKDIR
rm -r $WORKDIR
