#!/bin/bash
set -eu

TSH_KUBE_CLUSTER=${1}
TSH_PROXY=${TSH_KUBE_CLUSTER}
TSH_AUTH=${TSH_AUTH:-github}
TSH_USER=$(gh api user | jq -r .login)
TSH_BIND_ADDR=localhost:8000
CURRENT_CONTEXT=$(kubectl config current-context)

if [ -z "${TSH_USER}" -o "${TSH_USER}" = "null" ]; then
    echo -e "\e[31mERROR: Fail to fetch github user name.\e[m"
    exit 1
fi

tsh kube login --proxy ${TSH_PROXY} --auth ${TSH_AUTH} --user ${TSH_USER} --bind-addr ${TSH_BIND_ADDR} ${TSH_KUBE_CLUSTER}
if [ "$(kubectl config current-context)" != "${TSH_PROXY}-${TSH_KUBE_CLUSTER}" ]; then
    echo -e "\e[31mERROR: Fail to log in teleport server.\e[m"
    exit 1
fi
if kubectl config get-contexts ${TSH_KUBE_CLUSTER} &> /dev/null; then
    kubectl config delete-context ${TSH_KUBE_CLUSTER}
fi
kubectl config rename-context $(kubectl config current-context) ${TSH_KUBE_CLUSTER}
kubectl config use-context ${CURRENT_CONTEXT}
