#!/bin/bash
###################################
# Log in teleport server.
###################################

set -eu

TELEPORT_CLUSTER="${2:-${1}}"
TELEPORT_KUBE_CLUSTER="${1}"
TELEPORT_PROXY="${1}:443"

tsh login --proxy="${TELEPORT_PROXY}" "${TELEPORT_CLUSTER}"
tsh kube login "${TELEPORT_KUBE_CLUSTER}"
