#!/bin/bash
########################################
# kubectl plugin for Argo Workflows
########################################

set -e

bin=argo

if [ ! $(command -v ${bin}) ]; then
    echo "${bin} is not installed"
    exit 1
fi

if [ "$1" = "d" ] || [ "$1" = "dashboard" ]; then
    shift
    ${bin} server --secure=false --auth-mode=server --port 8000 $@
    exit $?
fi

${bin} $@
