#!/bin/bash

set -euo pipefail

COMMAND=$(basename "${0}")

function usage {
    cat <<EOF
NAME
    ${COMMAND}

SYNOPSIS
    ${COMMAND} [options] id

DESCRIPTION
    Retrieve the JSON execution plan from HCP Terraform.
    https://developer.hashicorp.com/terraform/cloud-docs/api-docs/plans#retrieve-the-json-execution-plan

OPTIONS
    -h  help for ${COMMAND}
EOF
}

while getopts h OPT
do
    case $OPT in
        h) usage; exit;;
        *) usage; exit 1;;
    esac
done

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

TOKEN=$(jq -r '.credentials["app.terraform.io"].token' "${HOME}/.terraform.d/credentials.tfrc.json")
curl -s --header "Authorization: Bearer ${TOKEN}" --header "Content-Type: application/vnd.api+json" --location "https://app.terraform.io/api/v2/runs/${1}/plan/json-output" | jq .
