#!/bin/bash
##################################################
# Update default audio devices
##################################################

printlog() {
    local level=$1
    local msg=${@:2}
    echo "[$level] $msg"
}

current_source() {
    echo "$pacmd_info" | grep "Default source name" | sed -e "s/Default source name: //g"
}

current_sink() {
    echo "$pacmd_info" | grep "Default sink name" | sed -e "s/Default sink name: //g"
}

device_connected() {
    echo "$pacmd_info" | grep "name: <$1>" > /dev/null
}

contain() {
    local item=$1
    local array=${@:2}
    for elem in ${array}
    do
        if [ $item == $elem ]; then
            return 0
        fi
    done
    return 1
}

SOURCE_WHITELIST=(
    # MARANTZ M4U (1st priority)
    "alsa_input.usb-C-Media_Electronics_Inc._MARANTZ_M4U_20190520-00.mono-fallback"
)

SINK_WHITELIST=(
    # WF-1000XM3 sink (1st priority) 
    "bluez_sink.38_18_4C_47_7B_B4.a2dp_sink"
    # Build-in (2nd priority)
    "alsa_output.pci-0000_00_1f.3.analog-stereo"
)

while true
do
    pacmd_info=$(pacmd info)

    if ! contain $(current_source) ${SOURCE_WHITELIST[@]}; then
        for desired_source in ${SOURCE_WHITELIST[@]}
        do
            if device_connected $desired_source; then
                printlog "INFO" "Source device update from \"$(current_source)\" to \"$desired_source\""
                pacmd set-default-source $desired_source
                break
            fi
        done
    fi

    if ! contain $(current_sink) ${SINK_WHITELIST[@]}; then
        for desired_sink in ${SINK_WHITELIST[@]}
        do
            if device_connected $desired_sink; then
                printlog "INFO" "Sink device update from \"$(current_sink)\" to \"$desired_sink\""
                pacmd set-default-sink $desired_sink
                break
            fi
        done
    fi

    sleep 5
done
