#!/bin/bash
##################################################
# Update default audio devices
##################################################

printlog() {
    local level=$1
    local msg=${@:2}
    echo "[$level] $msg"
}

current_source() {
    echo "$pacmd_info" | grep "Default source name" | sed -e "s/Default source name: //g"
}

current_sink() {
    echo "$pacmd_info" | grep "Default sink name" | sed -e "s/Default sink name: //g"
}

device_connected() {
    echo "$pacmd_info" | grep "name: <$1>" > /dev/null
}

contain() {
    local item=$1
    local array=${@:2}
    for elem in ${array}
    do
        if [ $item == $elem ]; then
            return 0
        fi
    done
    return 1
}

SOURCE_WHITELIST=(
    # MARANTZ M4U (default)
    "alsa_input.usb-C-Media_Electronics_Inc._MARANTZ_M4U_20190520-00.mono-fallback"
)

SINK_WHITELIST=(
    # Build-in (default)
    "alsa_output.pci-0000_00_1f.3.analog-stereo"
    # WF-1000XM3 sink
    "bluez_sink.38_18_4C_47_7B_B4.a2dp_sink"
)

DEFAULT_SOURCE=${SOURCE_WHITELIST[0]}
DEFAULT_SINK=${SINK_WHITELIST[0]}

while true
do
    pacmd_info=$(pacmd info)

    if ! contain $(current_source) ${SOURCE_WHITELIST[@]}; then
        if device_connected $DEFAULT_SOURCE; then
            printlog "INFO" "Source device update from \"$(current_source)\" to \"$DEFAULT_SOURCE\""
            pacmd set-default-source $DEFAULT_SOURCE
        fi
    fi

    if ! contain $(current_sink) ${SINK_WHITELIST[@]}; then
        if device_connected $DEFAULT_SINK; then
            printlog "INFO" "Sink device update from \"$(current_sink)\" to \"$DEFAULT_SINK\""
            pacmd set-default-sink $DEFAULT_SINK
        fi
    fi

    sleep 5
done
